#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIAttachmentEntityDto
@end

@interface OAIAttachmentEntityDto : OAIObject

/* The unique identifier for this attachment. 
 */
@property(nonatomic) NSString* _id;
/* The identifier of the attachment file 
 */
@property(nonatomic) NSString* attachmentId;
/* The user identifier associated with this attachment. 
 */
@property(nonatomic) NSString* userId;
/* The content type of the attachment. [optional]
 */
@property(nonatomic) NSString* contentType;
/* The content length of the attachment in bytes. [optional]
 */
@property(nonatomic) NSNumber* contentLength;
/* The content identifier, which is a unique ID for the content part of the email. [optional]
 */
@property(nonatomic) NSString* contentId;
/* The name of the attachment file. [optional]
 */
@property(nonatomic) NSString* name;
/* The inbox identifier associated with this attachment. [optional]
 */
@property(nonatomic) NSString* inboxId;
/* The timestamp when this attachment was created. 
 */
@property(nonatomic) NSDate* createdAt;
/* The timestamp when this attachment was last updated. 
 */
@property(nonatomic) NSDate* updatedAt;

@end
