#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIAttachmentMetaData
@end

@interface OAIAttachmentMetaData : OAIObject

/* Name of attachment if given [optional]
 */
@property(nonatomic) NSString* name;
/* Content type of attachment such as `image/png` [optional]
 */
@property(nonatomic) NSString* contentType;
/* Size of attachment in bytes [optional]
 */
@property(nonatomic) NSNumber* contentLength;
/* ID of attachment [optional]
 */
@property(nonatomic) NSString* _id;

@end
