#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAICreateCampaignProbeRunOptions
@end

@interface OAICreateCampaignProbeRunOptions : OAIObject

/* Sender email address [optional]
 */
@property(nonatomic) NSString* fromAddress;
/* Message subject [optional]
 */
@property(nonatomic) NSString* subject;
/* Recipient email address for context [optional]
 */
@property(nonatomic) NSString* recipient;
/* Caller supplied message id for dedupe/trace [optional]
 */
@property(nonatomic) NSString* messageId;
/* HTML body content to analyze [optional]
 */
@property(nonatomic) NSString* htmlBody;
/* Text body content to analyze when HTML is absent [optional]
 */
@property(nonatomic) NSString* textBody;

@end
