#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIDNSLookupOptions
@end

@interface OAIDNSLookupOptions : OAIObject

/* List of record types you wish to query such as MX, DNS, TXT, NS, A etc. 
 */
@property(nonatomic) NSString* hostname;
/* List of record types you wish to query such as MX, DNS, TXT, NS, A etc. 
 */
@property(nonatomic) NSArray<NSString*>* recordTypes;
/* Optionally control whether to omit the final dot in full DNS name values. [optional]
 */
@property(nonatomic) NSNumber* omitFinalDNSDot;

@end
