#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIEmailRecipientsProjection.h"
#import "OAISenderProjection.h"
@protocol OAIEmailRecipientsProjection;
@class OAIEmailRecipientsProjection;
@protocol OAISenderProjection;
@class OAISenderProjection;



@protocol OAIEmailThreadProjection
@end

@interface OAIEmailThreadProjection : OAIObject


@property(nonatomic) OAISenderProjection* sender;

@property(nonatomic) OAIEmailRecipientsProjection* recipients;
/* User ID 
 */
@property(nonatomic) NSString* userId;
/* Inbox ID [optional]
 */
@property(nonatomic) NSString* inboxId;
/* Updated at DateTime 
 */
@property(nonatomic) NSDate* updatedAt;
/* Created at DateTime 
 */
@property(nonatomic) NSDate* createdAt;
/* To recipients 
 */
@property(nonatomic) NSArray<NSString*>* to;
/* CC recipients [optional]
 */
@property(nonatomic) NSArray<NSString*>* cc;
/* BCC recipients [optional]
 */
@property(nonatomic) NSArray<NSString*>* bcc;
/* Has attachments 
 */
@property(nonatomic) NSNumber* hasAttachments;
/* Has unread 
 */
@property(nonatomic) NSNumber* unread;
/* Number of messages in the thread 
 */
@property(nonatomic) NSNumber* messageCount;
/* Last body excerpt [optional]
 */
@property(nonatomic) NSString* lastBodyExcerpt;
/* Last text excerpt [optional]
 */
@property(nonatomic) NSString* lastTextExcerpt;
/* Last email created time [optional]
 */
@property(nonatomic) NSDate* lastCreatedAt;
/* Last sender [optional]
 */
@property(nonatomic) NSString* lastFrom;

@property(nonatomic) OAISenderProjection* lastSender;
/* Thread topic subject [optional]
 */
@property(nonatomic) NSString* subject;
/* ID of email thread 
 */
@property(nonatomic) NSString* _id;
/* From sender [optional]
 */
@property(nonatomic) NSString* from;

@end
