#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIEmailAuditSpellingIssue.h"
#import "OAIEmailAuditUrlIssue.h"
#import "OAIEmailFeatureSupportResult.h"
#import "OAIHTMLValidationResult.h"
@protocol OAIEmailAuditSpellingIssue;
@class OAIEmailAuditSpellingIssue;
@protocol OAIEmailAuditUrlIssue;
@class OAIEmailAuditUrlIssue;
@protocol OAIEmailFeatureSupportResult;
@class OAIEmailFeatureSupportResult;
@protocol OAIHTMLValidationResult;
@class OAIHTMLValidationResult;



@protocol OAIEmailAuditAnalysisResult
@end

@interface OAIEmailAuditAnalysisResult : OAIObject

/* Health status for a one-shot email audit 
 */
@property(nonatomic) NSString* status;

@property(nonatomic) NSNumber* healthScore;

@property(nonatomic) NSNumber* totalChecks;

@property(nonatomic) NSNumber* passingChecks;

@property(nonatomic) NSNumber* failingChecks;

@property(nonatomic) NSNumber* detectedLinks;

@property(nonatomic) NSNumber* checkedLinks;

@property(nonatomic) NSNumber* detectedImages;

@property(nonatomic) NSNumber* checkedImages;

@property(nonatomic) NSNumber* linkIssueCount;

@property(nonatomic) NSNumber* imageIssueCount;

@property(nonatomic) NSNumber* spellingIssueCount;

@property(nonatomic) NSArray<OAIEmailAuditUrlIssue>* brokenLinks;

@property(nonatomic) NSArray<OAIEmailAuditUrlIssue>* brokenImages;

@property(nonatomic) NSArray<OAIEmailAuditSpellingIssue>* spellingIssues;

@property(nonatomic) NSNumber* compatibilityWarningCount;

@property(nonatomic) NSNumber* compatibilityNotSupportedCount;

@property(nonatomic) NSNumber* compatibilityUnknownCount;

@property(nonatomic) OAIEmailFeatureSupportResult* featureSupport;

@property(nonatomic) NSNumber* htmlErrorCount;

@property(nonatomic) NSNumber* htmlWarningCount;

@property(nonatomic) NSNumber* htmlInfoCount;

@property(nonatomic) OAIHTMLValidationResult* htmlValidation;

@property(nonatomic) NSNumber* reputationFailureCount;

@property(nonatomic) NSNumber* attachmentMentionIssueCount;

@property(nonatomic) NSNumber* externalCheckSkippedCount;

@property(nonatomic) NSArray<NSString*>* insights;

@property(nonatomic) NSString* errorMessage;

@end
