#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIEmailRecipients.h"
#import "OAISender.h"
@protocol OAIEmailRecipients;
@class OAIEmailRecipients;
@protocol OAISender;
@class OAISender;



@protocol OAIEmailThreadDto
@end

@interface OAIEmailThreadDto : OAIObject

/* ID of email thread 
 */
@property(nonatomic) NSString* _id;
/* User ID 
 */
@property(nonatomic) NSString* userId;
/* Inbox ID [optional]
 */
@property(nonatomic) NSString* inboxId;
/* From sender [optional]
 */
@property(nonatomic) NSString* from;
/* To recipients 
 */
@property(nonatomic) NSArray<NSString*>* to;
/* CC recipients [optional]
 */
@property(nonatomic) NSArray<NSString*>* cc;
/* BCC recipients [optional]
 */
@property(nonatomic) NSArray<NSString*>* bcc;

@property(nonatomic) OAISender* sender;

@property(nonatomic) OAIEmailRecipients* recipients;
/* Thread topic subject [optional]
 */
@property(nonatomic) NSString* subject;
/* Created at DateTime 
 */
@property(nonatomic) NSDate* createdAt;
/* Updated at DateTime 
 */
@property(nonatomic) NSDate* updatedAt;

@end
