#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIExtractCodesOptions
@end

@interface OAIExtractCodesOptions : OAIObject

/* Extraction strategy for verification codes. Unsupported strategies may fall back when allowFallback is true. [optional]
 */
@property(nonatomic) NSString* method;
/* Allow fallback to deterministic pattern extraction when the selected method is unavailable. [optional]
 */
@property(nonatomic) NSNumber* allowFallback;
/* Minimum code length to consider. Typical OTP values are between 4 and 8 characters. [optional]
 */
@property(nonatomic) NSNumber* minLength;
/* Maximum code length to consider. [optional]
 */
@property(nonatomic) NSNumber* maxLength;
/* Maximum number of code candidates to return. Best candidate is also returned separately. [optional]
 */
@property(nonatomic) NSNumber* maxCandidates;
/* Optional custom regex patterns for code extraction. Each pattern should have either one capture group for the code or match the full code directly. [optional]
 */
@property(nonatomic) NSArray<NSString*>* customPatterns;

@end
