#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIStructuredOutputSchema.h"
@protocol OAIStructuredOutputSchema;
@class OAIStructuredOutputSchema;



@protocol OAIStructuredOutputSchema
@end

@interface OAIStructuredOutputSchema : OAIObject


@property(nonatomic) NSArray<OAIStructuredOutputSchema>* anyOf;

@property(nonatomic) NSObject* _default;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSArray<NSString*>* _enum;

@property(nonatomic) NSObject* example;

@property(nonatomic) NSString* format;

@property(nonatomic) OAIStructuredOutputSchema* items;

@property(nonatomic) NSNumber* maxItems;

@property(nonatomic) NSNumber* minItems;

@property(nonatomic) NSNumber* maxLength;

@property(nonatomic) NSNumber* minLength;

@property(nonatomic) NSString* pattern;

@property(nonatomic) NSDictionary<OAIStructuredOutputSchema>* properties;

@property(nonatomic) NSArray<NSString*>* propertyOrdering;

@property(nonatomic) NSArray<NSString*>* required;

@property(nonatomic) NSNumber* maxProperties;

@property(nonatomic) NSNumber* minProperties;

@property(nonatomic) NSNumber* maximum;

@property(nonatomic) NSNumber* minimum;

@property(nonatomic) NSNumber* nullable;

@property(nonatomic) NSString* title;
/* Primitive JSON schema types with a fallback CUSTOM for unknown values. [optional]
 */
@property(nonatomic) NSString* type;

@end
