#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAISearchEmailsOptions
@end

@interface OAISearchEmailsOptions : OAIObject

/* Optional inbox ids to filter by. Can be repeated. By default will use all inboxes belonging to your account. [optional]
 */
@property(nonatomic) NSArray<NSString*>* inboxIds;
/* Optional page index in email list pagination [optional]
 */
@property(nonatomic) NSNumber* pageIndex;
/* Optional page size in email list pagination. Maximum size is 100. Use page index and sort to page through larger results [optional]
 */
@property(nonatomic) NSNumber* pageSize;
/* Optional createdAt sort direction ASC or DESC [optional]
 */
@property(nonatomic) NSString* sortDirection;
/* Optional filter for unread emails only. All emails are considered unread until they are viewed in the dashboard or requested directly [optional]
 */
@property(nonatomic) NSNumber* unreadOnly;
/* Optional search filter. Searches email recipients, sender, subject, email address and ID. Does not search email body [optional]
 */
@property(nonatomic) NSString* searchFilter;
/* Optional filter emails received after given date time [optional]
 */
@property(nonatomic) NSDate* since;
/* Optional filter emails received before given date time [optional]
 */
@property(nonatomic) NSDate* before;

@end
