#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIDeliverabilityExpectation.h"
@protocol OAIDeliverabilityExpectation;
@class OAIDeliverabilityExpectation;



@protocol OAIUpdateDeliverabilityTestOptions
@end

@interface OAIUpdateDeliverabilityTestOptions : OAIObject

/* Optional updated name [optional]
 */
@property(nonatomic) NSString* name;
/* Optional updated description [optional]
 */
@property(nonatomic) NSString* _description;
/* Optional updated receive-window start time. Only applied while test is not terminal. [optional]
 */
@property(nonatomic) NSDate* startAt;
/* Optional updated timeout in seconds [optional]
 */
@property(nonatomic) NSNumber* maxDurationSeconds;
/* Set true to clear timeout. If true, maxDurationSeconds is ignored for this request. [optional]
 */
@property(nonatomic) NSNumber* clearMaxDuration;
/* Optional updated acceptable success threshold percentage (0,100]. [optional]
 */
@property(nonatomic) NSNumber* successThresholdPercent;
/* Set true to clear success threshold. If true, successThresholdPercent is ignored for this request. [optional]
 */
@property(nonatomic) NSNumber* clearSuccessThreshold;
/* Optional replacement expectations [optional]
 */
@property(nonatomic) NSArray<OAIDeliverabilityExpectation>* expectations;

@end
