#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
*
* The version of the OpenAPI document: 6.5.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIWebhookNewContactPayload
@end

@interface OAIWebhookNewContactPayload : OAIObject


@property(nonatomic) NSString* company;

@property(nonatomic) NSString* contactId;

@property(nonatomic) NSDate* createdAt;

@property(nonatomic) NSArray<NSString*>* emailAddresses;
/* Name of the event type webhook is being triggered for. [optional]
 */
@property(nonatomic) NSString* eventName;

@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* groupId;

@property(nonatomic) NSString* lastName;
/* Idempotent message ID. Store this ID locally or in a database to prevent message duplication. [optional]
 */
@property(nonatomic) NSString* messageId;

@property(nonatomic) NSObject* metaData;

@property(nonatomic) NSNumber* optOut;

@property(nonatomic) NSString* primaryEmailAddress;

@property(nonatomic) NSArray<NSString*>* tags;
/* ID of webhook entity being triggered [optional]
 */
@property(nonatomic) NSString* webhookId;
/* Name of the webhook being triggered [optional]
 */
@property(nonatomic) NSString* webhookName;

@end
