#import <Foundation/Foundation.h>
#import "OAIGenerateStructuredContentAttachmentOptions.h"
#import "OAIGenerateStructuredContentEmailOptions.h"
#import "OAIStructuredContentResult.h"
#import "OAIStructuredOutputSchema.h"
#import "OAIStructuredOutputSchemaValidation.h"
#import "OAIApi.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIAIControllerApi: NSObject <OAIApi>

extern NSString* kOAIAIControllerApiErrorDomain;
extern NSInteger kOAIAIControllerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Generate structured content for an attachment
/// Use output schemas to extract data from an attachment using AI
///
/// @param generateStructuredContentAttachmentOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIStructuredContentResult*
-(NSURLSessionTask*) generateStructuredContentFromAttachmentWithGenerateStructuredContentAttachmentOptions: (OAIGenerateStructuredContentAttachmentOptions*) generateStructuredContentAttachmentOptions
    completionHandler: (void (^)(OAIStructuredContentResult* output, NSError* error)) handler;


/// Generate structured content for an email
/// Use output schemas to extract data from an email using AI
///
/// @param generateStructuredContentEmailOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIStructuredContentResult*
-(NSURLSessionTask*) generateStructuredContentFromEmailWithGenerateStructuredContentEmailOptions: (OAIGenerateStructuredContentEmailOptions*) generateStructuredContentEmailOptions
    completionHandler: (void (^)(OAIStructuredContentResult* output, NSError* error)) handler;


/// Validate structured content schema
/// Check if a schema is valid and can be used to extract data using AI
///
/// @param structuredOutputSchema 
/// 
///  code:200 message:"OK"
///
/// @return OAIStructuredOutputSchemaValidation*
-(NSURLSessionTask*) validateStructuredOutputSchemaWithStructuredOutputSchema: (OAIStructuredOutputSchema*) structuredOutputSchema
    completionHandler: (void (^)(OAIStructuredOutputSchemaValidation* output, NSError* error)) handler;



@end
