#import <Foundation/Foundation.h>
#import "OAIOptInConsentOptions.h"
#import "OAIOptInConsentSendResult.h"
#import "OAIOptInSendingConsentDto.h"
#import "OAIPageOptInIdentityProjection.h"
#import "OAIApi.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIConsentControllerApi: NSObject <OAIApi>

extern NSString* kOAIConsentControllerApiErrorDomain;
extern NSInteger kOAIConsentControllerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param emailAddress Email address to check consent for
/// 
///  code:200 message:"OK"
///
/// @return OAIOptInSendingConsentDto*
-(NSURLSessionTask*) checkSendingConsentForEmailAddressWithEmailAddress: (NSString*) emailAddress
    completionHandler: (void (^)(OAIOptInSendingConsentDto* output, NSError* error)) handler;


/// 
/// 
///
/// @param page Optional page index in list pagination (optional) (default to @0)
/// @param size Optional page size in list pagination (optional) (default to @20)
/// @param sort Optional createdAt sort direction ASC or DESC (optional) (default to @"ASC")
/// 
///  code:200 message:"OK"
///
/// @return OAIPageOptInIdentityProjection*
-(NSURLSessionTask*) getOptInIdentitiesWithPage: (NSNumber*) page
    size: (NSNumber*) size
    sort: (NSString*) sort
    completionHandler: (void (^)(OAIPageOptInIdentityProjection* output, NSError* error)) handler;


/// 
/// 
///
/// @param emailAddress Email address to revoke consent for
/// 
///  code:200 message:"OK"
///
/// @return OAIOptInSendingConsentDto*
-(NSURLSessionTask*) revokeOptInConsentForEmailAddressWithEmailAddress: (NSString*) emailAddress
    completionHandler: (void (^)(OAIOptInSendingConsentDto* output, NSError* error)) handler;


/// Send a verification code to a user once they have explicitly submitted their email address
/// Send double-opt in consent for an email address
///
/// @param optInConsentOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIOptInConsentSendResult*
-(NSURLSessionTask*) sendOptInConsentForEmailAddressWithOptInConsentOptions: (OAIOptInConsentOptions*) optInConsentOptions
    completionHandler: (void (^)(OAIOptInConsentSendResult* output, NSError* error)) handler;



@end
