#import <Foundation/Foundation.h>
#import "OAICancelDevicePreviewRunOptions.h"
#import "OAICancelDevicePreviewRunResult.h"
#import "OAICreateDevicePreviewFeedbackOptions.h"
#import "OAICreateDevicePreviewOptions.h"
#import "OAICreateDevicePreviewRunResult.h"
#import "OAIDeleteDevicePreviewRunResult.h"
#import "OAIDevicePreviewFeedbackDto.h"
#import "OAIDevicePreviewFeedbackListDto.h"
#import "OAIDevicePreviewProviderProgressDto.h"
#import "OAIDevicePreviewRunDto.h"
#import "OAIDevicePreviewRunResultsDto.h"
#import "OAIPageDevicePreviewRunProjection.h"
#import "OAIUpdateDevicePreviewFeedbackOptions.h"
#import "OAIApi.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIDevicePreviewsControllerApi: NSObject <OAIApi>

extern NSString* kOAIDevicePreviewsControllerApiErrorDomain;
extern NSInteger kOAIDevicePreviewsControllerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Cancel a running device preview run
/// 
///
/// @param runId 
/// @param cancelDevicePreviewRunOptions  (optional)
/// 
///  code:200 message:"OK"
///
/// @return OAICancelDevicePreviewRunResult*
-(NSURLSessionTask*) cancelDevicePreviewRunWithRunId: (NSString*) runId
    cancelDevicePreviewRunOptions: (OAICancelDevicePreviewRunOptions*) cancelDevicePreviewRunOptions
    completionHandler: (void (^)(OAICancelDevicePreviewRunResult* output, NSError* error)) handler;


/// Create device preview feedback
/// 
///
/// @param createDevicePreviewFeedbackOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIDevicePreviewFeedbackDto*
-(NSURLSessionTask*) createDevicePreviewFeedbackWithCreateDevicePreviewFeedbackOptions: (OAICreateDevicePreviewFeedbackOptions*) createDevicePreviewFeedbackOptions
    completionHandler: (void (^)(OAIDevicePreviewFeedbackDto* output, NSError* error)) handler;


/// Create a new device preview run for an email
/// 
///
/// @param emailId 
/// @param createDevicePreviewOptions  (optional)
/// 
///  code:200 message:"OK"
///
/// @return OAICreateDevicePreviewRunResult*
-(NSURLSessionTask*) createDevicePreviewRunWithEmailId: (NSString*) emailId
    createDevicePreviewOptions: (OAICreateDevicePreviewOptions*) createDevicePreviewOptions
    completionHandler: (void (^)(OAICreateDevicePreviewRunResult* output, NSError* error)) handler;


/// Delete local device preview run data
/// 
///
/// @param runId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeleteDevicePreviewRunResult*
-(NSURLSessionTask*) deleteDevicePreviewRunWithRunId: (NSString*) runId
    completionHandler: (void (^)(OAIDeleteDevicePreviewRunResult* output, NSError* error)) handler;


/// Return active run for email or create one when none exists
/// 
///
/// @param emailId 
/// @param createDevicePreviewOptions  (optional)
/// 
///  code:200 message:"OK"
///
/// @return OAICreateDevicePreviewRunResult*
-(NSURLSessionTask*) ensureDevicePreviewRunWithEmailId: (NSString*) emailId
    createDevicePreviewOptions: (OAICreateDevicePreviewOptions*) createDevicePreviewOptions
    completionHandler: (void (^)(OAICreateDevicePreviewRunResult* output, NSError* error)) handler;


/// Get a single device preview feedback item
/// 
///
/// @param feedbackId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDevicePreviewFeedbackDto*
-(NSURLSessionTask*) getDevicePreviewFeedbackWithFeedbackId: (NSString*) feedbackId
    completionHandler: (void (^)(OAIDevicePreviewFeedbackDto* output, NSError* error)) handler;


/// List device preview feedback
/// 
///
/// @param page  (optional)
/// @param size  (optional)
/// @param source  (optional)
/// @param runId  (optional)
/// @param status  (optional)
/// @param provider  (optional)
/// @param category  (optional)
/// @param search  (optional)
/// 
///  code:200 message:"OK"
///
/// @return OAIDevicePreviewFeedbackListDto*
-(NSURLSessionTask*) getDevicePreviewFeedbackItemsWithPage: (NSNumber*) page
    size: (NSNumber*) size
    source: (NSString*) source
    runId: (NSString*) runId
    status: (NSString*) status
    provider: (NSString*) provider
    category: (NSString*) category
    search: (NSString*) search
    completionHandler: (void (^)(OAIDevicePreviewFeedbackListDto* output, NSError* error)) handler;


/// Get device preview run status
/// 
///
/// @param runId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDevicePreviewRunDto*
-(NSURLSessionTask*) getDevicePreviewRunWithRunId: (NSString*) runId
    completionHandler: (void (^)(OAIDevicePreviewRunDto* output, NSError* error)) handler;


/// Get provider-level progress for a device preview run
/// 
///
/// @param runId 
/// @param provider 
/// 
///  code:200 message:"OK"
///
/// @return OAIDevicePreviewProviderProgressDto*
-(NSURLSessionTask*) getDevicePreviewRunProviderProgressWithRunId: (NSString*) runId
    provider: (NSString*) provider
    completionHandler: (void (^)(OAIDevicePreviewProviderProgressDto* output, NSError* error)) handler;


/// Get device preview run results
/// 
///
/// @param runId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDevicePreviewRunResultsDto*
-(NSURLSessionTask*) getDevicePreviewRunResultsWithRunId: (NSString*) runId
    completionHandler: (void (^)(OAIDevicePreviewRunResultsDto* output, NSError* error)) handler;


/// Get a seeded device preview screenshot image
/// 
///
/// @param runId 
/// @param screenshotId 
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) getDevicePreviewRunScreenshotWithRunId: (NSString*) runId
    screenshotId: (NSString*) screenshotId
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// List previous device preview runs for an email
/// 
///
/// @param emailId 
/// @param limit  (optional) (default to @50)
/// 
///  code:200 message:"OK"
///
/// @return NSArray<OAIDevicePreviewRunDto>*
-(NSURLSessionTask*) getDevicePreviewRunsWithEmailId: (NSString*) emailId
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<OAIDevicePreviewRunDto>* output, NSError* error)) handler;


/// List previous device preview runs for account
/// 
///
/// @param limit  (optional) (default to @50)
/// 
///  code:200 message:"OK"
///
/// @return NSArray<OAIDevicePreviewRunDto>*
-(NSURLSessionTask*) getDevicePreviewRunsForAccountWithLimit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<OAIDevicePreviewRunDto>* output, NSError* error)) handler;


/// List previous device preview runs for an email in paginated form
/// 
///
/// @param emailId 
/// @param page Optional page index in list pagination (optional) (default to @0)
/// @param size Optional page size for paginated result list. (optional) (default to @20)
/// @param sort Optional createdAt sort direction ASC or DESC (optional) (default to @"DESC")
/// 
///  code:200 message:"OK"
///
/// @return OAIPageDevicePreviewRunProjection*
-(NSURLSessionTask*) getDevicePreviewRunsOffsetPaginatedWithEmailId: (NSString*) emailId
    page: (NSNumber*) page
    size: (NSNumber*) size
    sort: (NSString*) sort
    completionHandler: (void (^)(OAIPageDevicePreviewRunProjection* output, NSError* error)) handler;


/// Update device preview feedback
/// 
///
/// @param feedbackId 
/// @param updateDevicePreviewFeedbackOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIDevicePreviewFeedbackDto*
-(NSURLSessionTask*) updateDevicePreviewFeedbackWithFeedbackId: (NSString*) feedbackId
    updateDevicePreviewFeedbackOptions: (OAIUpdateDevicePreviewFeedbackOptions*) updateDevicePreviewFeedbackOptions
    completionHandler: (void (^)(OAIDevicePreviewFeedbackDto* output, NSError* error)) handler;



@end
