#import <Foundation/Foundation.h>
#import "OAICreateDeliverabilitySimulationJobOptions.h"
#import "OAICreateDeliverabilityTestOptions.h"
#import "OAIDeleteResult.h"
#import "OAIDeliverabilityAnalyticsSeriesDto.h"
#import "OAIDeliverabilityEntityResultPageDto.h"
#import "OAIDeliverabilityFailureHotspotsDto.h"
#import "OAIDeliverabilityPollStatusResultDto.h"
#import "OAIDeliverabilitySimulationJobDto.h"
#import "OAIDeliverabilitySimulationJobEventPageDto.h"
#import "OAIDeliverabilityTestDto.h"
#import "OAIDeliverabilityTestPageDto.h"
#import "OAIUpdateDeliverabilityTestOptions.h"
#import "OAIApi.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIDeliverabilityTestControllerApi: NSObject <OAIApi>

extern NSString* kOAIDeliverabilityTestControllerApiErrorDomain;
extern NSInteger kOAIDeliverabilityTestControllerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Cancel deliverability simulation job
/// Cancel a running or paused simulation job.
///
/// @param testId 
/// @param jobId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilitySimulationJobDto*
-(NSURLSessionTask*) cancelDeliverabilitySimulationJobWithTestId: (NSString*) testId
    jobId: (NSString*) jobId
    completionHandler: (void (^)(OAIDeliverabilitySimulationJobDto* output, NSError* error)) handler;


/// Create deliverability simulation job
/// Create and start a simulation job for a running deliverability test. Only one active simulation job is allowed per user.
///
/// @param testId 
/// @param createDeliverabilitySimulationJobOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilitySimulationJobDto*
-(NSURLSessionTask*) createDeliverabilitySimulationJobWithTestId: (NSString*) testId
    createDeliverabilitySimulationJobOptions: (OAICreateDeliverabilitySimulationJobOptions*) createDeliverabilitySimulationJobOptions
    completionHandler: (void (^)(OAIDeliverabilitySimulationJobDto* output, NSError* error)) handler;


/// Create deliverability/load test
/// Create a deliverability test for inboxes or phone numbers using ALL, PATTERN, or EXPLICIT selector scope.
///
/// @param createDeliverabilityTestOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityTestDto*
-(NSURLSessionTask*) createDeliverabilityTestWithCreateDeliverabilityTestOptions: (OAICreateDeliverabilityTestOptions*) createDeliverabilityTestOptions
    completionHandler: (void (^)(OAIDeliverabilityTestDto* output, NSError* error)) handler;


/// Delete deliverability/load test
/// Delete test and all persisted entity-level results.
///
/// @param testId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeleteResult*
-(NSURLSessionTask*) deleteDeliverabilityTestWithTestId: (NSString*) testId
    completionHandler: (void (^)(OAIDeleteResult* output, NSError* error)) handler;


/// Duplicate deliverability/load test
/// Create a fresh deliverability test using an existing test configuration, including selector scope, exclusions, and expectations.
///
/// @param testId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityTestDto*
-(NSURLSessionTask*) duplicateDeliverabilityTestWithTestId: (NSString*) testId
    completionHandler: (void (^)(OAIDeliverabilityTestDto* output, NSError* error)) handler;


/// Export deliverability/load test report as PDF
/// Export a PDF report for a terminal deliverability test (COMPLETE, FAILED, or STOPPED), including configuration, summary outcomes, and detailed entity-level results.
///
/// @param testId 
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) exportDeliverabilityTestReportWithTestId: (NSString*) testId
    completionHandler: (void (^)(NSError* error)) handler;


/// Export deliverability/load test entity results as CSV
/// Export per-entity deliverability results including expectation-level pass/fail counts. The latest status is evaluated with the same polling safeguards before export.
///
/// @param testId 
/// @param matched  (optional)
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) exportDeliverabilityTestResultsWithTestId: (NSString*) testId
    matched: (NSNumber*) matched
    completionHandler: (void (^)(NSError* error)) handler;


/// Get deliverability analytics time series
/// Compare deliverability runs over a time range with bucketed chart metrics and run-level rows for table views.
///
/// @param since  (optional)
/// @param before  (optional)
/// @param scope  (optional)
/// @param bucket  (optional) (default to @"DAY")
/// @param runLimit  (optional)
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityAnalyticsSeriesDto*
-(NSURLSessionTask*) getDeliverabilityAnalyticsSeriesWithSince: (NSDate*) since
    before: (NSDate*) before
    scope: (NSString*) scope
    bucket: (NSString*) bucket
    runLimit: (NSNumber*) runLimit
    completionHandler: (void (^)(OAIDeliverabilityAnalyticsSeriesDto* output, NSError* error)) handler;


/// Get deliverability failure hotspots
/// Find commonly failing entities and phone country/variant dimensions across deliverability runs in a time range.
///
/// @param since  (optional)
/// @param before  (optional)
/// @param scope  (optional)
/// @param limit  (optional)
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityFailureHotspotsDto*
-(NSURLSessionTask*) getDeliverabilityFailureHotspotsWithSince: (NSDate*) since
    before: (NSDate*) before
    scope: (NSString*) scope
    limit: (NSNumber*) limit
    completionHandler: (void (^)(OAIDeliverabilityFailureHotspotsDto* output, NSError* error)) handler;


/// Get deliverability simulation job
/// Get simulation job status and progress counters.
///
/// @param testId 
/// @param jobId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilitySimulationJobDto*
-(NSURLSessionTask*) getDeliverabilitySimulationJobWithTestId: (NSString*) testId
    jobId: (NSString*) jobId
    completionHandler: (void (^)(OAIDeliverabilitySimulationJobDto* output, NSError* error)) handler;


/// Get deliverability simulation job events
/// Get paged simulation events including send successes and failures.
///
/// @param testId 
/// @param jobId 
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @20)
/// @param sort  (optional) (default to @"DESC")
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilitySimulationJobEventPageDto*
-(NSURLSessionTask*) getDeliverabilitySimulationJobEventsWithTestId: (NSString*) testId
    jobId: (NSString*) jobId
    page: (NSNumber*) page
    size: (NSNumber*) size
    sort: (NSString*) sort
    completionHandler: (void (^)(OAIDeliverabilitySimulationJobEventPageDto* output, NSError* error)) handler;


/// Get deliverability/load test
/// Get deliverability test configuration and latest progress counters.
///
/// @param testId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityTestDto*
-(NSURLSessionTask*) getDeliverabilityTestWithTestId: (NSString*) testId
    completionHandler: (void (^)(OAIDeliverabilityTestDto* output, NSError* error)) handler;


/// Get deliverability/load test entity results
/// Get paged per-entity expectation results with optional matched/unmatched filtering.
///
/// @param testId 
/// @param matched  (optional)
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @20)
/// @param sort  (optional) (default to @"ASC")
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityEntityResultPageDto*
-(NSURLSessionTask*) getDeliverabilityTestResultsWithTestId: (NSString*) testId
    matched: (NSNumber*) matched
    page: (NSNumber*) page
    size: (NSNumber*) size
    sort: (NSString*) sort
    completionHandler: (void (^)(OAIDeliverabilityEntityResultPageDto* output, NSError* error)) handler;


/// List deliverability/load tests
/// List deliverability tests for the authenticated account.
///
/// @param page Page index (optional) (default to @0)
/// @param size Page size (optional) (default to @20)
/// @param sort Sort direction (optional) (default to @"DESC")
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityTestPageDto*
-(NSURLSessionTask*) getDeliverabilityTestsWithPage: (NSNumber*) page
    size: (NSNumber*) size
    sort: (NSString*) sort
    completionHandler: (void (^)(OAIDeliverabilityTestPageDto* output, NSError* error)) handler;


/// Get latest deliverability simulation job
/// Get the most recent simulation job for a deliverability test.
///
/// @param testId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilitySimulationJobDto*
-(NSURLSessionTask*) getLatestDeliverabilitySimulationJobWithTestId: (NSString*) testId
    completionHandler: (void (^)(OAIDeliverabilitySimulationJobDto* output, NSError* error)) handler;


/// Pause deliverability simulation job
/// Pause a running simulation job.
///
/// @param testId 
/// @param jobId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilitySimulationJobDto*
-(NSURLSessionTask*) pauseDeliverabilitySimulationJobWithTestId: (NSString*) testId
    jobId: (NSString*) jobId
    completionHandler: (void (^)(OAIDeliverabilitySimulationJobDto* output, NSError* error)) handler;


/// Pause deliverability/load test
/// Pause a RUNNING or SCHEDULED deliverability test.
///
/// @param testId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityTestDto*
-(NSURLSessionTask*) pauseDeliverabilityTestWithTestId: (NSString*) testId
    completionHandler: (void (^)(OAIDeliverabilityTestDto* output, NSError* error)) handler;


/// Poll deliverability/load test status
/// Poll test progress. Evaluation is throttled with a 5-second cache window to protect backing data stores.
///
/// @param testId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityPollStatusResultDto*
-(NSURLSessionTask*) pollDeliverabilityTestStatusWithTestId: (NSString*) testId
    completionHandler: (void (^)(OAIDeliverabilityPollStatusResultDto* output, NSError* error)) handler;


/// Resume deliverability simulation job
/// Resume a paused simulation job.
///
/// @param testId 
/// @param jobId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilitySimulationJobDto*
-(NSURLSessionTask*) resumeDeliverabilitySimulationJobWithTestId: (NSString*) testId
    jobId: (NSString*) jobId
    completionHandler: (void (^)(OAIDeliverabilitySimulationJobDto* output, NSError* error)) handler;


/// Start or resume deliverability/load test
/// Start a CREATED test or resume a PAUSED/SCHEDULED test.
///
/// @param testId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityTestDto*
-(NSURLSessionTask*) startDeliverabilityTestWithTestId: (NSString*) testId
    completionHandler: (void (^)(OAIDeliverabilityTestDto* output, NSError* error)) handler;


/// Stop deliverability/load test
/// Stop a deliverability test and mark it terminal.
///
/// @param testId 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityTestDto*
-(NSURLSessionTask*) stopDeliverabilityTestWithTestId: (NSString*) testId
    completionHandler: (void (^)(OAIDeliverabilityTestDto* output, NSError* error)) handler;


/// Update deliverability/load test
/// Update metadata, timeout, and expectations for a non-running non-terminal test.
///
/// @param testId 
/// @param updateDeliverabilityTestOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIDeliverabilityTestDto*
-(NSURLSessionTask*) updateDeliverabilityTestWithTestId: (NSString*) testId
    updateDeliverabilityTestOptions: (OAIUpdateDeliverabilityTestOptions*) updateDeliverabilityTestOptions
    completionHandler: (void (^)(OAIDeliverabilityTestDto* output, NSError* error)) handler;



@end
