#import <Foundation/Foundation.h>
#import "OAIPageEmailValidationRequest.h"
#import "OAIValidateEmailAddressListOptions.h"
#import "OAIValidateEmailAddressListResult.h"
#import "OAIApi.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIEmailVerificationControllerApi: NSObject <OAIApi>

extern NSString* kOAIEmailVerificationControllerApiErrorDomain;
extern NSInteger kOAIEmailVerificationControllerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Delete all validation requests
/// 
///
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) deleteAllValidationRequestsWithCompletionHandler: 
    (void (^)(NSError* error)) handler;


/// Delete a validation record
/// 
///
/// @param _id 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) deleteValidationRequestWithId: (NSString*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Validate a list of email addresses. Per unit billing. See your plan for pricing.
/// 
///
/// @param page Optional page index in list pagination (optional) (default to @0)
/// @param size Optional page size for paginated result list. (optional) (default to @20)
/// @param sort Optional createdAt sort direction ASC or DESC (optional) (default to @"DESC")
/// @param searchFilter Optional search filter (optional)
/// @param since Filter by created at after the given timestamp (optional)
/// @param before Filter by created at before the given timestamp (optional)
/// @param isValid Filter where email is valid is true or false (optional)
/// 
///  code:200 message:"OK"
///
/// @return OAIPageEmailValidationRequest*
-(NSURLSessionTask*) getValidationRequestsWithPage: (NSNumber*) page
    size: (NSNumber*) size
    sort: (NSString*) sort
    searchFilter: (NSString*) searchFilter
    since: (NSDate*) since
    before: (NSDate*) before
    isValid: (NSNumber*) isValid
    completionHandler: (void (^)(OAIPageEmailValidationRequest* output, NSError* error)) handler;


/// Validate a list of email addresses. Per unit billing. See your plan for pricing.
/// 
///
/// @param validateEmailAddressListOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIValidateEmailAddressListResult*
-(NSURLSessionTask*) validateEmailAddressListWithValidateEmailAddressListOptions: (OAIValidateEmailAddressListOptions*) validateEmailAddressListOptions
    completionHandler: (void (^)(OAIValidateEmailAddressListResult* output, NSError* error)) handler;



@end
