#import <Foundation/Foundation.h>
#import "OAIDNSLookupOptions.h"
#import "OAIDNSLookupResults.h"
#import "OAIDescribeDomainOptions.h"
#import "OAIDescribeMailServerDomainResult.h"
#import "OAIEmailVerificationResult.h"
#import "OAIIPAddressResult.h"
#import "OAIVerifyEmailAddressOptions.h"
#import "OAIApi.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIMailServerControllerApi: NSObject <OAIApi>

extern NSString* kOAIMailServerControllerApiErrorDomain;
extern NSInteger kOAIMailServerControllerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get DNS Mail Server records for a domain
/// 
///
/// @param describeDomainOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIDescribeMailServerDomainResult*
-(NSURLSessionTask*) describeMailServerDomainWithDescribeDomainOptions: (OAIDescribeDomainOptions*) describeDomainOptions
    completionHandler: (void (^)(OAIDescribeMailServerDomainResult* output, NSError* error)) handler;


/// Lookup DNS records for a domain
/// 
///
/// @param dNSLookupOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIDNSLookupResults*
-(NSURLSessionTask*) getDnsLookupWithDNSLookupOptions: (OAIDNSLookupOptions*) dNSLookupOptions
    completionHandler: (void (^)(OAIDNSLookupResults* output, NSError* error)) handler;


/// Get IP address for a domain
/// 
///
/// @param name 
/// 
///  code:200 message:"OK"
///
/// @return OAIIPAddressResult*
-(NSURLSessionTask*) getIpAddressWithName: (NSString*) name
    completionHandler: (void (^)(OAIIPAddressResult* output, NSError* error)) handler;


/// Verify the existence of an email address at a given mail server.
/// 
///
/// @param verifyEmailAddressOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIEmailVerificationResult*
-(NSURLSessionTask*) verifyEmailAddressWithVerifyEmailAddressOptions: (OAIVerifyEmailAddressOptions*) verifyEmailAddressOptions
    completionHandler: (void (^)(OAIEmailVerificationResult* output, NSError* error)) handler;



@end
