#import <Foundation/Foundation.h>
#import "OAICreateEmergencyAddressOptions.h"
#import "OAIEmergencyAddress.h"
#import "OAIEmergencyAddressDto.h"
#import "OAIEmptyResponseDto.h"
#import "OAIPagePhoneNumberProjection.h"
#import "OAIPhoneNumberDto.h"
#import "OAIPhonePlanDto.h"
#import "OAITestPhoneNumberOptions.h"
#import "OAIApi.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIPhoneControllerApi: NSObject <OAIApi>

extern NSString* kOAIPhoneControllerApiErrorDomain;
extern NSInteger kOAIPhoneControllerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param createEmergencyAddressOptions 
/// 
///  code:200 message:"OK"
///
/// @return OAIEmergencyAddress*
-(NSURLSessionTask*) createEmergencyAddressWithCreateEmergencyAddressOptions: (OAICreateEmergencyAddressOptions*) createEmergencyAddressOptions
    completionHandler: (void (^)(OAIEmergencyAddress* output, NSError* error)) handler;


/// 
/// 
///
/// @param addressId 
/// 
///  code:200 message:"OK"
///
/// @return OAIEmptyResponseDto*
-(NSURLSessionTask*) deleteEmergencyAddressWithAddressId: (NSString*) addressId
    completionHandler: (void (^)(OAIEmptyResponseDto* output, NSError* error)) handler;


/// 
/// 
///
/// @param phoneNumberId 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) deletePhoneNumberWithPhoneNumberId: (NSString*) phoneNumberId
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// 
///
/// @param addressId 
/// 
///  code:200 message:"OK"
///
/// @return OAIEmergencyAddress*
-(NSURLSessionTask*) getEmergencyAddressWithAddressId: (NSString*) addressId
    completionHandler: (void (^)(OAIEmergencyAddress* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"OK"
///
/// @return NSArray<OAIEmergencyAddressDto>*
-(NSURLSessionTask*) getEmergencyAddressesWithCompletionHandler: 
    (void (^)(NSArray<OAIEmergencyAddressDto>* output, NSError* error)) handler;


/// 
/// 
///
/// @param phoneNumberId 
/// 
///  code:200 message:"OK"
///
/// @return OAIPhoneNumberDto*
-(NSURLSessionTask*) getPhoneNumberWithPhoneNumberId: (NSString*) phoneNumberId
    completionHandler: (void (^)(OAIPhoneNumberDto* output, NSError* error)) handler;


/// 
/// 
///
/// @param page Optional page index for list pagination (optional) (default to @0)
/// @param size Optional page size for list pagination (optional) (default to @20)
/// @param sort Optional createdAt sort direction ASC or DESC (optional) (default to @"ASC")
/// @param since Filter by created at after the given timestamp (optional)
/// @param before Filter by created at before the given timestamp (optional)
/// 
///  code:200 message:"OK"
///
/// @return OAIPagePhoneNumberProjection*
-(NSURLSessionTask*) getPhoneNumbersWithPage: (NSNumber*) page
    size: (NSNumber*) size
    sort: (NSString*) sort
    since: (NSDate*) since
    before: (NSDate*) before
    completionHandler: (void (^)(OAIPagePhoneNumberProjection* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"OK"
///
/// @return NSArray<OAIPhonePlanDto>*
-(NSURLSessionTask*) getPhonePlansWithCompletionHandler: 
    (void (^)(NSArray<OAIPhonePlanDto>* output, NSError* error)) handler;


/// 
/// 
///
/// @param phoneNumberId 
/// @param testPhoneNumberOptions 
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) testPhoneNumberSendSmsWithPhoneNumberId: (NSString*) phoneNumberId
    testPhoneNumberOptions: (OAITestPhoneNumberOptions*) testPhoneNumberOptions
    completionHandler: (void (^)(NSError* error)) handler;



@end
